# -*- coding: utf-8 -*-
"""Age of Abalone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18zLLumS06OQX8F3FUpDZ_INMzG9kou7v
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import io
df = pd.read_csv(io.BytesIO(uploaded['abalone.csv']))

df.info()

df.describe()

df.dtypes

df.drop('Sex',axis=1,inplace=True)

df.drop(['Rings'], axis = 1)

df.head()

y = df['Rings']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state= 5)

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

#Support Vector Machine

from sklearn.svm import SVC
svc_classifier2 = SVC()
svc_classifier2.fit(X_train_sc, y_train)
y_pred_svc_sc = svc_classifier2.predict(X_test_sc)
accuracy_score(y_test, y_pred_svc_sc)

#Naive_Bayes

from sklearn.naive_bayes import GaussianNB
nb_classifier2 = GaussianNB()
nb_classifier2.fit(X_train_sc, y_train)
y_pred_nb_sc = nb_classifier2.predict(X_test_sc)
accuracy_score(y_test, y_pred_nb_sc)

#Decision Tree

from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 51)
dt_classifier.fit(X_train, y_train)
y_pred_dt = dt_classifier.predict(X_test)
accuracy_score(y_test, y_pred_dt)

import matplotlib.pyplot as plt
import seaborn as sns

#Generating HEATMAP

plt.figure(figsize=(10,10))
sns.heatmap(df.corr(), annot = True, cmap ='coolwarm', linewidths=2)